name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install Dependencies
      run: go mod tidy

    - name: Build
      run: go build -v ./...

    - name: Run Tests with Coverage
      run: |
        mkdir -p coverage
        go test -v -coverprofile=coverage/coverage.out ./...

    - name: Check Test Coverage
      run: |
        if [ ! -f coverage/coverage.out ]; then
          echo "No coverage report generated. Test suite might be empty."
          exit 1
        fi
        coverage=$(go tool cover -func=coverage/coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
        echo "Coverage is $coverage%"
        if (( $(echo "$coverage < 80" | awk '{print ($1 < 80)}') )); then
          echo "Test coverage ($coverage%) is below 80%"
          exit 1
        fi

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/coverage.out
