name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install Dependencies
      run: go mod tidy

    - name: Build
      run: go build -v ./...

    - name: Run Tests with Coverage
      run: |
        mkdir -p coverage
        go test -coverprofile=coverage/coverage.out ./...

    - name: Generate Coverage Summary
      run: |
        go tool cover -func=coverage/coverage.out > coverage/coverage-summary.txt

    - name: Generate Coverage Badge
      run: |
        coverage=$(go tool cover -func=coverage/coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
        echo "Coverage: $coverage%"
        color="red"
        if (( $(echo "$coverage >= 80" | bc -l) )); then
          color="green"
        elif (( $(echo "$coverage >= 50" | bc -l) )); then
          color="yellow"
        fi
        curl -o coverage/badge.svg "https://img.shields.io/badge/coverage-$coverage%25-$color"

    - name: Update README with Coverage Badge
      run: |
        if grep -q "\!\[Coverage\]" README.md; then
          sed -i "s|!\[Coverage\](.*)|![Coverage](coverage/badge.svg)|" README.md
        else
          echo "![Coverage](coverage/badge.svg)" >> README.md
        fi

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/
