name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...

    - name: Run Tests with Coverage
      run: |
        mkdir -p coverage
        go test -v -coverprofile=coverage/coverage.out ./...

    - name: Check Test Coverage
      run: |
        coverage=$(go tool cover -func=coverage/coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
        echo "Coverage is $coverage%"
        if (( $(echo "$coverage < 80" | bc -l) )); then
          echo "Test coverage ($coverage%) is below 80%"
          exit 1
        fi
