name: BuildAndTest

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install Dependencies
      run: go mod tidy

    - name: Build
      run: go build -v ./...

    - name: Run Tests with Coverage
      run: |
        mkdir -p coverage
        go test -coverprofile=coverage/coverage.out ./...

    - name: Generate Coverage Summary
      run: |
        go tool cover -func=coverage/coverage.out > coverage/coverage-summary.txt
        cat coverage/coverage-summary.txt

    - name: Generate Coverage Badge
      run: |
        coverage=$(go tool cover -func=coverage/coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
        echo "Coverage: $coverage%"
        
        if (( $(echo "$coverage < ${{ secrets.COVERAGE }}" | bc -l) )); then
          color="red"
        elif (( $(echo "$coverage >= 50" | bc -l) )); then
          color="yellow"
        else
          color="green"
        fi

        echo "https://img.shields.io/badge/coverage-$coverage%25-$color"
        curl -o coverage/badge.svg "https://img.shields.io/badge/coverage-$coverage%25-$color"

    - name: Install lcov
      run: sudo apt-get install -y lcov

    - name: Convert Coverage to lcov Format
      run: |
        genhtml coverage/coverage.out --output-directory coverage/
        mv coverage/index.html coverage/coverage.lcov

    - name: Coveralls
      uses: coverallsapp/github-action@v2.3.0
      with:
        github-token: ${{ secrets.github_token }}
        file: coverage/coverage.out
        format: golang

    - name: Combine Coverage Files
      run: |
        lcov --add-tracefile ./coverage/coverage.lcov -o ./coverage/combined.info

    - name: Report Coverage
      uses: zgosalvez/github-actions-report-lcov@v1
      with:
        coverage-files: coverage/combined.info
        minimum-coverage: ${{ secrets.COVERAGE }}
        artifact-name: code-coverage-report

    - name: Commit and Push Coverage Badge
      if: always()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git fetch origin
        git checkout ${{ github.head_ref || github.ref_name }}
        git pull origin ${{ github.head_ref || github.ref_name }}
        git add coverage/badge.svg
        git commit -m "Update coverage badge [skip ci]" || echo "No changes to commit"
        git push origin HEAD:${{ github.head_ref || github.ref_name }}
